name: pytest

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Run pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest
